### ISSUE TITLE
TURN anonymous auth is not supported

### ISSUE THREAD

**Issue by AndyEsser** [pion/webrtc#1896] opened 2021-07-22 14:26 UTC
Your environment.
Version: v3
Browser: Chrome 91.0.4472.164
What did you do?
Attempting to create an application that connects to an existing WebRTC platform, able to successfully create a connection locally (host), or without relaying (srflx) but unable to relay via a coTURN server that is known to be working.

ICE Configuration
```
ICEServers: []webrtc.ICEServer{
		{
			URLs:       []string{"turn:relay.dev.haia.live:443?transport=tcp"},
			Username:   "swarm",
			Credential: s.Source,
			CredentialType: webrtc.ICECredentialTypePassword,
		},
		{
			URLs:       []string{"turn:relay.dev.haia.live:443?transport=udp"},
			Username:   "swarm",
			Credential: s.Source,
			CredentialType: webrtc.ICECredentialTypePassword,
		},
		{
			URLs:       []string{"turn:relay.dev.haia.live:80?transport=tcp"},
			Username:   "swarm",
			Credential: s.Source,
			CredentialType: webrtc.ICECredentialTypePassword,
		},
		{
			URLs:       []string{"turn:relay.dev.haia.live:80?transport=udp"},
			Username:   "swarm",
			Credential: s.Source,
			CredentialType: webrtc.ICECredentialTypePassword,
		},
	},
```

Example returned Candidates
```
candidate="{candidate:3312907880 1 udp 2130706431 192.168.1.205 56893 typ host 0xc000164210 0xc00009c13a <nil>}"
candidate="{candidate:750502208 1 udp 2130706431 10.0.251.6 65012 typ host 0xc00021a250 0xc0002480ca <nil>}"
candidate="{candidate:3178305033 1 udp 1694498815 <public-ip> 51635 typ srflx raddr 0.0.0.0 rport 51635 0xc0003237e0 0xc00038db5a <nil>}"
candidate="{candidate:3178305033 1 udp 1694498815 <public-ip> 62141 typ srflx raddr 0.0.0.0 rport 62141 0xc000268330 0xc00029235e <nil>}"
candidate="{candidate:3178305033 1 udp 1694498815 <public-ip> 64126 typ srflx raddr 0.0.0.0 rport 64126 0xc00021a000 0xc00026006e <nil>}"
candidate="{candidate:3178305033 1 udp 1694498815 <public-ip> 64007 typ srflx raddr 0.0.0.0 rport 64007 0xc00024c050 0xc00009c0aa <nil>}"
```

What did you expect?
During Candidate Gathering to see Relay type candidates

What happened?
Only Host and SRFLX type Candidates are provided

**Comment by Sean-Der** [comment] 2021-07-22 14:34
Hey @AndyEsser

We do have E2E tests around TURN so it *should* be working. Maybe we are missing a feature in the TURN server you are using (I have only tested with coturn + pion turn).

Can you try turning on the trace logging for TURN and then maybe ICE as well if nothing is helpful.

`export PION_LOG_TRACE=turn` and then `PION_LOG_TRACE=ice`

If you feel comfortable sharing credentials could you send them to me either sean@pion.ly or Sean-Der on Slack?

thanks!

**Comment by AndyEsser** [comment] 2021-07-22 14:46
Hi Sean,

Thanks for your speedy response.

The TURN server is actually Credential-less at the moment, so you should be able to just `turn:stick relay.dev.haia.live:443` to test.

Additionally, I've tested it with https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ with both transport=tcp and no transport parameter specified, and it returns relay candidates.

```
Time	Component	Type	Foundation	Protocol	Address	Port	Priority
0.004	rtp	host	49269444	udp	192.168.1.205	65123	126 | 32542 | 255
0.007	rtp	host	105682689	udp	10.0.251.6	50153	126 | 32286 | 255
0.054	rtp	srflx	3849130477	udp	<public-ip>	50153	100 | 32286 | 255
0.077	rtp	relay	1166896211	udp	<turn-server-ip>	60064	2 | 32286 | 255
0.106	rtp	host	1282160180	tcp	192.168.1.205	9	90 | 32542 | 255
0.107	rtp	host	1221553137	tcp	10.0.251.6	9	90 | 32286 | 255
0.153	rtp	relay	185503907	udp	<turn-server-ip>	61329	1 | 32287 | 255
```

Also I tried to ping you on the Gopher slack but it says you are not on there.

`PION_LOG_TRACE=turn`

No additional logging

 `PION_LOG_TRACE=ice` 

Lots of logging regarding pining HOST and SRFLX candidates, and then find a candidate pair (SRFLX) no mentions at all about Relay - I can send all the logs over if you would like

**Comment by AndyEsser** [comment] 2021-07-23 13:44
Just a quick follow-up, I ran a local Pion TURN server (what I will eventually move our infrastructure towards, and away from coTURN) and direct the above to use that as it's TURN server in the ICE configuration.

Still no RELAY candidates printed out, so unsure if I'm missing something in the client to enable to try to gather relay candidates?

**Comment by Sean-Der** [comment] 2021-07-23 14:20
Hey @AndyEsser 

I am not able to reproduce, these are my steps locally I am using to confirm

```
* wget https://github.com/pion/turn/releases/download/v2.0.2/turn_2.0.2_Linux_x86_64.tar.gz
* tar xzvf turn_2.0.2_Linux_x86_64.tar.gz
* ./turn-server-simple -public-ip 127.0.0.1 -users foo=bar
```

This is my example program
```
package main

import (
        "fmt"

        "github.com/pion/webrtc/v3"
)

func main() {
        peerConnection, _ := webrtc.NewPeerConnection(webrtc.Configuration{
                ICEServers: []webrtc.ICEServer{
                        {
                                URLs:       []string{"turn:localhost"},
                                Username:   "foo",
                                Credential: "bar",
                        },
                },
        })

        peerConnection.CreateDataChannel("foobar", nil)

        offer, _ := peerConnection.CreateOffer(nil)

        gatherComplete := webrtc.GatheringCompletePromise(peerConnection)
        peerConnection.SetLocalDescription(offer)
        <-gatherComplete

        fmt.Println(*peerConnection.LocalDescription())
}
```

This is what it returns
```
v=0
o=- 4824057070673706729 1627049997 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 D8:1E:C2:5C:18:18:F2:9C:3C:72:C0:6A:3D:F5:0C:43:72:D1:B4:89:EA:A2:25:58:F3:82:2D:C4:57:DC:82:71
a=group:BUNDLE 0
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=sendrecv
a=sctp-port:5000
a=ice-ufrag:HdPrQmkPjtJamWyE
a=ice-pwd:IIgGznfnTOrmyfDSQvlesWsmPOKhxhUK
a=candidate:1740498230 1 udp 2130706431 192.168.0.5 51660 typ host
a=candidate:1740498230 2 udp 2130706431 192.168.0.5 51660 typ host
a=candidate:3528925834 1 udp 2130706431 172.18.0.1 48297 typ host
a=candidate:3528925834 2 udp 2130706431 172.18.0.1 48297 typ host
a=candidate:233762139 1 udp 2130706431 172.17.0.1 46973 typ host
a=candidate:233762139 2 udp 2130706431 172.17.0.1 46973 typ host
a=candidate:2193111953 1 udp 2130706431 172.20.0.1 58397 typ host
a=candidate:2193111953 2 udp 2130706431 172.20.0.1 58397 typ host
a=candidate:3308009161 1 udp 2130706431 172.19.0.1 41015 typ host
a=candidate:3308009161 2 udp 2130706431 172.19.0.1 41015 typ host
a=candidate:1152622311 1 udp 2130706431 10.10.0.1 57776 typ host
a=candidate:1152622311 2 udp 2130706431 10.10.0.1 57776 typ host
a=candidate:3835024012 1 udp 1694498815 127.0.0.1 39507 typ srflx raddr 0.0.0.0 rport 39507
a=candidate:3835024012 2 udp 1694498815 127.0.0.1 39507 typ srflx raddr 0.0.0.0 rport 39507
a=candidate:2847320077 1 udp 16777215 127.0.0.1 51540 typ relay raddr 0.0.0.0 rport 43125
a=candidate:2847320077 2 udp 16777215 127.0.0.1 51540 typ relay raddr 0.0.0.0 rport 43125
a=candidate:47591296 1 udp 2130706431 fda7:65f0:687a:a:fa2b:41ba:9d02:8189 47198 typ host
a=candidate:47591296 2 udp 2130706431 fda7:65f0:687a:a:fa2b:41ba:9d02:8189 47198 typ host
a=end-of-candidates
```

**Comment by AndyEsser** [comment] 2021-07-23 14:28
Hi Sean,

Many thanks for this.

If I run your sample code:

I get the following output (with Pion TURN server running locally)

```
 v=0
o=- 3664812956316667273 1627050387 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 19:B6:E3:46:7A:11:E1:C4:63:D9:41:95:B0:61:1A:32:19:39:49:1C:5F:2E:FE:EC:E5:90:C8:09:48:3E:4B:F3
a=group:BUNDLE 0
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=sendrecv
a=sctp-port:5000
a=ice-ufrag:KNtrBqPgNNoQTVzj
a=ice-pwd:ipNfRThEiVJzSfQGNroXTCMcIMqifLYE
a=candidate:3312907880 1 udp 2130706431 192.168.1.205 57079 typ host
a=candidate:3312907880 2 udp 2130706431 192.168.1.205 57079 typ host
a=candidate:750502208 1 udp 2130706431 10.0.251.6 52328 typ host
a=candidate:750502208 2 udp 2130706431 10.0.251.6 52328 typ host
a=end-of-candidates

```

I get the following output (with coTURN running at relay.dev.haia.live:443)

```
v=0
o=- 1631455336579060913 1627050294 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 BA:05:4A:3F:FC:29:8F:82:34:C3:CE:57:E7:23:FA:4A:9E:14:B3:D3:C5:6F:BF:08:B3:FC:FA:64:82:D1:16:31
a=group:BUNDLE 0
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=sendrecv
a=sctp-port:5000
a=ice-ufrag:IpICyFJYqhtQojAu
a=ice-pwd:IEolbYNpFxpXpBmFcStmrfpXzgTVvCLd
a=candidate:3312907880 1 udp 2130706431 192.168.1.205 50388 typ host
a=candidate:3312907880 2 udp 2130706431 192.168.1.205 50388 typ host
a=candidate:750502208 1 udp 2130706431 10.0.251.6 62058 typ host
a=candidate:750502208 2 udp 2130706431 10.0.251.6 62058 typ host
a=candidate:3178305033 1 udp 1694498815 18.135.29.34 53729 typ srflx raddr 0.0.0.0 rport 53729
a=candidate:3178305033 2 udp 1694498815 18.135.29.34 53729 typ srflx raddr 0.0.0.0 rport 53729
a=end-of-candidates
```

If you run your sample application with turn server set to `turn:relay.dev.haia.live:443`, any username/password is acceptable - do you get relay candidates?

**Comment by Sean-Der** [comment] 2021-07-23 14:45
That does fail! The issue is that pion/turn doesn't support anonymous auth.

Can you enable auth and share the credentials? Will try again.

[This](https://github.com/pion/turn/blob/master/client.go#L268) is the line that fails. I found that from this log line `ice WARNING: 2021/07/23 10:44:02 Failed to allocate on turn.Client relay.dev.haia.live:443 attribute not found`

**Comment by AndyEsser** [comment] 2021-07-23 14:50
Username: pion
Password: test123
Server: turn:relay.dev.haia.live:443

Result:

```
v=0
o=- 8966568273668201680 1627051700 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 05:BD:00:A4:95:AC:0F:A3:C6:80:96:7F:8B:96:45:09:70:42:9F:D8:F4:56:F2:0D:BA:1A:6B:4D:F0:15:D2:78
a=group:BUNDLE 0
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=sendrecv
a=sctp-port:5000
a=ice-ufrag:YGAccvaJqSIBAAsy
a=ice-pwd:MqhgopKTlCyxwdsUxpWMQIEzGoyriTuE
a=candidate:3312907880 1 udp 2130706431 192.168.1.205 49929 typ host
a=candidate:3312907880 2 udp 2130706431 192.168.1.205 49929 typ host
a=candidate:750502208 1 udp 2130706431 10.0.251.6 63319 typ host
a=candidate:750502208 2 udp 2130706431 10.0.251.6 63319 typ host
a=candidate:3178305033 1 udp 1694498815 18.135.29.34 52055 typ srflx raddr 0.0.0.0 rport 52055
a=candidate:3178305033 2 udp 1694498815 18.135.29.34 52055 typ srflx raddr 0.0.0.0 rport 52055
a=candidate:1023178942 1 udp 16777215 3.8.186.113 50098 typ relay raddr 0.0.0.0 rport 56575
a=candidate:1023178942 2 udp 16777215 3.8.186.113 50098 typ relay raddr 0.0.0.0 rport 56575
a=end-of-candidates
```

So it seems, you were spot on with this lack of support for anonymous auth. I guess I need to go back to an auth mechanism (although I am currently trying to roll out a new relay doing away with coTURN and instead using the Pion UDP/TCP/TLS TURN server package)

**Comment by Sean-Der** [comment] 2021-07-23 14:57
I can look into supporting anonymous auth if it is blocking you!

It would add more complexity to Pion, so if you don't really need it would prefer not to add it :)

**Comment by AndyEsser** [comment] 2021-07-23 14:59
Well, looking at your UDP/TCP/TLS Turn Server examples it looks like we can easily hook into the auth mechanism?

The reason I disabled auth is we were running into maximum allocations per user issues, and I couldn't find a nice way to dynamically generate User accounts for coTURN.

However, it seems Pion might well solve much of these issues anyway.

**Comment by Sean-Der** [comment] 2021-07-23 15:06
Maybe [lt-cred](https://github.com/pion/turn/tree/master/examples/lt-cred-generator) can get you around that limitation with coturn? I am not that familiar with coturn.

I have been playing around with the idea of making a 'batteries attached' distribution of pion/turn as well. Something that automatically figures out your public IP + letsencrypt. I love `pion/turn` as an API, but isn't matching what users need.

**Comment by Sean-Der** [comment] 2021-07-23 15:06
Closing as a won't fix for now, but happy to come back to this in the future if it blocks people.

**Closed** 2021-07-23 15:06 UTC
