### ISSUE TITLE
document calling PeerConnection.Close, add to examples

### ISSUE THREAD

**Issue by josharian** [pion/webrtc#1241] opened 2020-06-06 18:18 UTC
As discussed here:

https://gophers.slack.com/archives/CAK2124AG/p1591453173401600

**Comment by Sean-Der** [comment] 2020-06-09 07:37
It also would help a lot if we implemented https://github.com/pion/ice/issues/189

The ICE Agent would go to failed, and then all the resources would be freed without user interaction.

**Comment by Sean-Der** [comment] 2020-12-28 18:15
Duplicate of https://github.com/pion/webrtc/issues/839

**Closed by Sean-Der** 2020-12-28 18:15 UTC
Labels: documentation, help wanted
