### ISSUE TITLE
Send offer twice in very short time, second offer doesn't reflect well

### ISSUE THREAD

**Issue by Rollooo** [pion/webrtc#2054] opened 2021-12-16 10:00 UTC
### Your environment.
  - Version: v3.1.7
  - Browser: Chrome
  - Other Information - [peerconnection.go](https://github.com/pion/webrtc/blob/517a32639a98612814a4a230f1043530112908c4/peerconnection.go#L942)

### What did you do?
Send offer twice in very short time(within 100ms).
In the first offer, I just add datachannel in SDP
In the second offer, I add two tracks(audio, video)

But the second offer doesn't reflects well and see error log in PeerConnection as below
`Incoming unhandled RTP ssrc(123412341234), OnTrack will not be fired. incoming SSRC failed Simulcast probing`

This issue is raised because REMOTE DESCRIPTION is changed during processing the first offer's startRTP().
(startSCTP() takes long time for init)
So I think before completing startRTP() of the first offer, it should prevent to change REMOTE DESCRIPTION or filter the simulcastStream by undeclaredMediaProcessor(). 

And there is no way to check it startRTP() is in progress. Adding some function for checking it in PeerConnection might be helpful for user.

* I call PeerConnection's functions sequentially as below.
```
SetRemoteDescription(offer) -> answer, err := CreateAnswer(nil) -> SetLocalDescription(answer) 
```

### What did you expect?
The second offer should reflect well.

### What happened?
The  second offer doesn't reflect well

**Comment by Sean-Der** [comment] 2021-12-26 19:57
Hi @Rollooo 

Thanks for filing this issue! Is the issue is that if Pion is called with two different `SetRemoteDescription`s quickly the second one is ignored?

**Comment by Rollooo** [comment] 2021-12-27 02:08
Hi @Sean-Der 

The second one is not ignored, but offer/answer doesn't have SSRCes those filtered by `undeclaredMediaProcesser()`

If you add sleep at `startRTP()`(ex. <-time.After(time.Second * 2)) and SetRemoteDescription() twice time quickly. You may reproduce this issue easily.

**Comment by Sean-Der** [comment] 2021-12-27 03:50
Ok I think I understand more!

The issue is that Simulcast times out because the `SetRemoteDescription` hasn't happened yet?

So this would be fixed by setting [simulcastProbeCount](https://github.com/pion/webrtc/blob/master/constants.go#L17) to a very large number (like math.MaxInt)

Maybe we should re-attempt probing after every SetRemoteDescription?

**Comment by Rollooo** [comment] 2021-12-27 05:12
Okay, I will check this issue after increasing simulcastProbeCount.

**Comment by Rollooo** [comment] 2021-12-27 05:32
[simulcastProbeCount](https://github.com/pion/webrtc/blob/master/constants.go#L17) has no effect to this issue.
After increasing it, I saw the error log as below
`Incoming unhandled RTP ssrc(1234123412), OnTrack will not be fired. no trackStreams found for RID: f`

**Comment by Rollooo** [comment] 2021-12-29 02:20
@lamhai1401 Yes, I did
Even though I accepted the second offer after ice is connected, It didn't work well.
The first offer's startRTP() should be done  before accepting the second one.

**Closed** 2022-01-17 19:57 UTC

**Comment by Sean-Der** [comment] 2022-01-17 19:58
Hi @Rollooo 

Would you mind trying again with `v3.1.16` @boks1971 has fixed this with https://github.com/pion/webrtc/commit/04ca4493f690242eba60624e774094209b76971b

thank you!

**Comment by lamhai1401** [comment] 2022-01-26 08:13
@Sean-Der  @boks1971 
Hi guys, after i updated pion v3.1.16
My webrtc android app was crash everytime when peer connected

[webrtc version 1.0.32006](https://mvnrepository.com/artifact/org.webrtc/google-webrtc/1.0.32006)
This is my stderr:

<img width="794" alt="Screen Shot 2022-01-26 at 15 10 02" src="https://user-images.githubusercontent.com/31619361/151126012-9b7d922d-5436-4aa6-a0a3-b96beba16134.png">


Everything will be fine in pion v3.1.15

**Comment by boks1971** [comment] 2022-01-26 08:33
@lamhai1401 Is this on audio or video track or both?

If video only, does it happen for simulcast only or both simulcast and non-simulcast?

**Comment by lamhai1401** [comment] 2022-01-26 08:47
> @lamhai1401 Is this on audio or video track or both?
> 
> If video only, does it happen for simulcast only or both simulcast and non-simulcast?

This is `non-simulcast` peer, i did not check with `simulcast `.
When ICE states change to `connected` it will crash before `OnTrack` event was called, so i don't know which track.

**Comment by boks1971** [comment] 2022-01-26 08:51
Thank you for the details. Can you please add the SDP offer that causes the crash?

**Comment by lamhai1401** [comment] 2022-01-26 09:21
> Thank you for the details. Can you please add the SDP offer that causes the crash?
Yes sure! This is the offer.
[sdp.txt](https://github.com/pion/webrtc/files/7940374/sdp.txt)
Is there anything else i can help in this case?

**Comment by boks1971** [comment] 2022-01-26 10:42
Thank you. Looking at the code, not able to see the issue. The repair stream SSRC is probably not set up right because it looks like Flex FEC is ON, but that should not cause crash.

A couple of more things
1. Are you using Unified Plan or Plan B for SDP?
2. Do you have Pion logs? Want to check if start receiver failed for some reason.

**Comment by lamhai1401** [comment] 2022-01-26 11:08
> Thank you. Looking at the code, not able to see the issue. The repair stream SSRC is probably not set up right because it looks like Flex FEC is ON, but that should not cause crash.
> 
> A couple of more things
> 
> 1. Are you using Unified Plan or Plan B for SDP?
> 2. Do you have Pion logs? Want to check if start receiver failed for some reason.

1. Unified Plan
2. I checked pion log in stdout, it's show nothing.
3. I checked in my log file, peer will crash when ICE states change `connected`.
4. In my IOS device and web app, everything it's ok.

**Comment by boks1971** [comment] 2022-01-26 11:22
Thank you. Sorry for asking more stuff. But, it would be great if you can attach working samples too
1. SDP from iOS and web
2. Pion logs (even if you do not see error, would be great to get logs to look for any problematic looking flow)

**Comment by lamhai1401** [comment] 2022-01-27 06:37
> Thank you. Sorry for asking more stuff. But, it would be great if you can attach working samples too
> 
> 1. SDP from iOS and web
> 2. Pion logs (even if you do not see error, would be great to get logs to look for any problematic looking flow)

Yah no problem! Here is my report
+ 1 ios offer
+1 web offer
+ 1 stdout (empty) & 1 stderr was catch by pm2
+ 1 log file if you are interested in. At `10:44:09.971431156` process was crash after android peer ICE change to `connected`

I can start a debugging if you want me to collect more info.

Please download here!
[report.tar.gz](https://github.com/pion/webrtc/files/7948128/report.tar.gz)

**Comment by boks1971** [comment] 2022-01-27 06:51
Thank you @lamhai1401 . The one difference I see between iOS/Web and Android is Flex FEC. Let me look at Pion code to see why that would cause issues and how it was working before v3.1.15. Will let you know about help with debugging

**Comment by boks1971** [comment] 2022-01-27 08:06
@lamhai1401 Looking at the code more, I think it is the `FEC-FR` group in Android that is causing trouble. I think it is working in v3.1.15 because of timing of which stream arrives first at the server. Would you be able to turn off FEC on Android client?

**Comment by lamhai1401** [comment] 2022-01-27 08:58
> @lamhai1401 Looking at the code more, I think it is the `FEC-FR` group in Android that is causing trouble. I think it is working in v3.1.15 because of timing of which stream arrives first at the server. Would you be able to turn off FEC on Android client?
It's worked after i turn off `FEC-FR`.
Thanks you so much.
