### ISSUE TITLE
Add error handling to methods on public structs that `Self` is not nil

### ISSUE THREAD

**Issue by ecurbelo** [pion/webrtc#621] opened 2019-04-15 10:52 UTC
[main.go.log](https://github.com/pion/webrtc/files/3079627/main.go.log)

### Your environment.
  - Version: v2.0.7
  - Browser: not applicable
  - Other Information:
1. I coded two peers in Go (see attached file).
1. The initiator is called "Client" (creates the offer) and the other one, "Server" (receives the offer and creates the answer)
1. I use a Go channel (CommunicationChannel) to exchange the SDP messages.
1. When the datachannel Client is opened, sends a message to the Server ("Hi server!"). 
1. When the Server receives "Hi server!", responds with a "Hi client!" message.

### What did you do?
I build the attached file (rename first to main.go): `$ go build main.go `
And run it: `$ ./main`

### What did you expect?
See in console:
```
[SERVER] Message from DataChannel <testing>: Hi server! 
[SERVER] DataChannel opened <testing>: XXXXXXX
[CLIENT] Message received in data channel:  Hi client!
```

### What happened?
```
[...]
[CLIENT] Signaling state has changed:  stable
[CLIENT] ICE connection state has changed:  checking
[SERVER] ICE connection state has changed:  connected
[CLIENT] ICE connection state has changed:  connected
[CLIENT] Data channel opened!
[SERVER] PeerConnection New DataChannel <testing>: 824637983760 
[SERVER] Message from DataChannel <testing>: Hi server! 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x624e84]

goroutine 118 [running]:
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:48
github.com/pion/webrtc/v2.(*DataChannel).ensureOpen(0x0, 0x0, 0x0)
	/home/elena/projects/golang/pkg/mod/github.com/pion/webrtc/v2@v2.0.7/datachannel.go:320 +0x34
github.com/pion/webrtc/v2.(*DataChannel).SendText(0x0, 0x6d5102, 0xa, 0x2c, 0xc0002676f0)
	/home/elena/projects/golang/pkg/mod/github.com/pion/webrtc/v2@v2.0.7/datachannel.go:305 +0x2f
main.(*MyPeer).initServer.func4.3(0xc0003fa901, 0xc000492000, 0xa, 0x4000)
	/home/elena/projects/golang/src/sandbox/main.go:158 +0x166
github.com/pion/webrtc/v2.(*DataChannel).onMessage(0xc0003fa900, 0xc000492001, 0xc000492000, 0xa, 0x4000)
	/home/elena/projects/golang/pkg/mod/github.com/pion/webrtc/v2@v2.0.7/datachannel.go:246 +0x7e
github.com/pion/webrtc/v2.(*DataChannel).readLoop(0xc0003fa900)
	/home/elena/projects/golang/pkg/mod/github.com/pion/webrtc/v2@v2.0.7/datachannel.go:284 +0xee
created by github.com/pion/webrtc/v2.(*DataChannel).handleOpen
	/home/elena/projects/golang/pkg/mod/github.com/pion/webrtc/v2@v2.0.7/datachannel.go:260 +0xdc
```

If I uncomment the line #157 (`time.Sleep(1*time.Second)` on Server OnMessage event), the code works.

**Comment by backkem** [comment] 2019-04-15 11:16
Hi @ecurbelo, thanks for reaching out.

It seems the problem is that our `OnOpen` callback is asynchronous:
https://github.com/pion/webrtc/blob/481aec036f1c5faaffd585caab06db823d597db6/datachannel.go#L218-L221
Therefore, it's not guaranteed that `OnOpen` is called before the first `OnMessage` callback. That does seem inconsistent with the JavaScript world.

We'll have to look into how/if we can fix this since our examples currently have endless for-loops in the `OnOpen` callback. cc @Sean-Der: potential API change (sort of).

In the mean time you could use the data channel passed to `OnDataChannel`:
```go
err = dc.SendText("Hi client!")
```

**Comment by ecurbelo** [comment] 2019-04-15 11:30
Hi @backkem, thanks for your fast response.

If I change the function:
```
dc.OnMessage(func(msg webrtc.DataChannelMessage) {
			fmt.Printf("[SERVER] Message from DataChannel <%s>: %s \n", dc.Label(), string(msg.Data))
			//time.Sleep(1*time.Second)
			//err = p.dataChannel.SendText("Hi client!")
			err = dc.SendText("Hi client!")
			if nil != err {
				panic(err)
			}
		})
```

Fails the line #90 in Client: `err = p.peerConnection.SetRemoteDescription(*answer)`
```
panic: InvalidModificationError: invalid proposed signaling state transition have-local-offer->SetRemote(offer)->have-remote-offer

goroutine 6 [running]:
main.(*MyPeer).initClient(0xc00000ea20)
	/home/elena/projects/golang/src/sandbox/main.go:92 +0x6a9
created by main.main
	/home/elena/projects/golang/src/sandbox/main.go:28 +0x12e
```

I am doing something wrong? :thinking:

**Comment by maxhawkins** [comment] 2019-04-15 16:47
There is a race condition because both the client and server and blocking on `CommunicationChannel` at the same time.

If the client reaches `<-CommunicationChannel` before the server does the offer will be sent back to the client rather than to the server. The client will receive its own offer and attempt to set it as an answer. This is not allowed because it is expecting an answer from the server rather than an offer.

To fix, either use two different communication channels of each signaling direction or ensure that the client and server block on the channel in the correct order.

Here's a trace:
```
Init testing
[CLIENT] New peer connection:  &{{{0 0} 0 0 0 0} {[{[stun:stun.l.google.com:19302]  <nil> 0}] 2 1 2  [{0xc0000bb050 0xc00017e000}] 0 0} <nil> <nil> <nil> <nil> 1 1 1 1 <nil> false false   [] map[] <nil> <nil> <nil> <nil> <nil> <nil> 0xc000116460 0xc00011c480 0xc0001540a0 <nil> 0xc0000afa30 0xc0000cf500}
[CLIENT] New data channel:  &{{{0 0} 0 0 0 0} testing true <nil> <nil>  false 0xc000113930 0 1 0 <nil> <nil> <nil> <nil> <nil> <nil> 0xc0000afa30 0xc0000cf500}
[CLIENT] Generated offer
[CLIENT] Signaling state has changed:  have-local-offer
[CLIENT] ICE candidate gathering state has changed
[CLIENT] Updated offer
[CLIENT] Received answer
panic: InvalidModificationError: invalid proposed signaling state transition have-local-offer->SetRemote(offer)->have-remote-offer

goroutine 19 [running]:
main.(*MyPeer).initClient(0xc0000b8a60)
        /Users/max/Downloads/issue/main.go:92 +0x692
created by main.main
        /Users/max/Downloads/issue/main.go:28 +0x12e
exit status 2
```

**Comment by albrow** [comment] 2019-04-15 18:58
@Sean-Der @backkem I don't think we should change the API for `OnOpen` and other handlers. Blocking in the handler function can cause deadlocks that are particularly hard to debug. The JavaScript API is also non-blocking, so if we were to change our handlers to blocking, it would be an API mismatch.

We can still improve error handling for cases like this (returning an error instead of panicking) and maybe even add clarification to the documentation about the fact that handler functions are non-blocking. What do you think?

**Comment by Sean-Der** [comment] 2019-04-16 00:33
@backkem @albrow 

In the short term should we add guards to every `Datachannel` method. It could go a long way to helping people debug in the future.  Then we never have to crash someone at runtime with `SendText` was called on a `nil` pointer :(

I think it is fine that the order of callbacks is not guaranteed (`OnOpen` vs `OnMessage`). We have had so many bugs from people blocking these callbacks, I think it would bite more people in the long run.

**Comment by ecurbelo** [comment] 2019-04-16 15:18
Sorry for taking time to respond. :(

@maxhawkins Thanks! I created two channels and now is working fine in that example. My real code (where the server is an API REST) is still not working tho.  :( 

I'll try to do a simple example and test again. Can I ask you not to close this ticket yet?

@albrow @Sean-Der Thank you, too.

**Comment by Sean-Der** [comment] 2019-04-16 20:50
@ecurbelo

Are you hitting this same segfault in your REST API? 

Can you save the `DataChannel` from the `OnMessage` OR `OpenOpen` (and make sure to use a mutex they both run in goroutines) just which ever fires first should set the `datachannel` object.

We will keep the ticket open! I do want to make code changes so in the future we return an error (and not a SEGV) if you are interested in contributing to Pion would love to help you make this change :)

**Comment by ecurbelo** [comment] 2019-04-17 07:20
@Sean-Der Yes, I have a segmentation fault when I tested my API REST with a Go test function. But I coded another project with the minimum code and that works! So, surely it is my fault, I have so many Go channels to check errors, timeouts, etc.

I'll do a refactor and I'll fix it. Thank you so much for your help, guys. If I have time, I'll collaborate with your project. You can close this issue now. :)

**Comment by Sean-Der** [comment] 2020-01-30 08:34
I am resolving this for now, but feel free to re-open if you disagree. These are my thoughts for now.

* We haven't gotten any other bug reports about this being an issue
* We have no way to enforce these checks are added properly. We can add them to the code base, but there is no tooling to ensure new structs in the future have this check
* They add code complexity and may have a runtime cost.
* This is something that can happen with stdlib code as well. I think we should keep with established patterns.
```
    f := tls.Conn{}
    f.Close()
```

**Closed by Sean-Der** 2020-01-30 08:34 UTC
Labels: difficulty:easy, good first issue
