### ISSUE TITLE
Dynamic RTP payload types break streaming in non Chromium browsers

### ISSUE THREAD

**Issue by matt-allan** [pion/webrtc#2237] opened 2022-05-23 15:24 UTC
### Your environment.
  - Version: 3.1.34
  - Browser: Firefox 100.0.2 (on MacOS and Arch Linux)

Ran the [pion/mediadevices webrtc example](https://github.com/pion/mediadevices/tree/master/examples/webrtc)

### What did you expect?

The example to work in major browsers

### What happened?

The example works fine in Chromium based browsers. In Firefox everything connects correctly and the video stream shows it is playing but there's no output. The audio stream does not play. Same issue with desktop Safari, mobile Firefox, and mobile Safari.

I ran into the same issue with the VP8 codec. I wasn't able to get a stream working with Safari iOS either. I think it was the same issue but haven't confirmed yet.

### Additional info

Here's the SDP log for a failed session in Firefox: https://gist.github.com/matt-allan/4bbed61755adc9cb5ef67a8e8dbe226a

This is what `about:webrtc` looks like when this is happening:

<img width="1670" alt="Screen Shot 2022-05-23 at 10 54 06 AM" src="https://user-images.githubusercontent.com/9440455/169853229-0f26ae5f-cf35-4497-8bb4-a3b48e560bd5.png">

And this is what  I'm seeing:

<img width="723" alt="Screen Shot 2022-05-23 at 10 59 36 AM" src="https://user-images.githubusercontent.com/9440455/169853277-81b67097-b780-46df-8f37-9c40447e6a4a.png">

This is what I see for desktop Safari:

<img width="396" alt="Screen Shot 2022-05-23 at 11 26 03 AM" src="https://user-images.githubusercontent.com/9440455/169854008-be24236d-3064-4f7b-82d2-51e8082f09d9.png">

### Debugging notes

I've found a lot of previous issues suggesting this is caused by Pion using a hardcoded payload type for the RTP packets when they should be dynamic. It works in Chrome because the payload type matches what Chrome uses. It doesn't work in Firefox because Firefox uses different type IDs than Chrome.

I was able to confirm that changing the payload type from 125 to 126 (because Firefox is trying to use 126) in [`codec.go`](https://github.com/pion/mediadevices/blob/69f9cbe0082c6adc59d7df98dc57d934e756b7b1/pkg/codec/codec.go#L34) of the mediadevices package fixes the issue for Firefox. However I'm filing an issue here and not a PR in that repo since it appears to be an issue with the core webrtc code and not the mediadevices codec.

From what I can tell it's expected for browsers to use dynamic payload types:

> payload type
   values in the range 96-127 MAY be defined dynamically through a
   conference control protocol
https://www.rfc-editor.org/rfc/rfc3551.html#section-6

> For some (older) codecs like PCMU the payload type is assigned statically as described in [RFC3551](https://datatracker.ietf.org/doc/html/rfc3551). For others, it is assigned dynamically through the SDP. Note: there are no guarantees on the stability of a payload type assignment.
> For this allocation, the range from 96 to 127 is used.

https://webrtc.googlesource.com/src/+/HEAD/pc/g3doc/rtp.md

The [doc comment for payloadType](https://github.com/pion/webrtc/blob/7367daf2324b66290f0bdbaab1e51297de1f4989/rtpcodec.go#L72) indicates it can be negotiated. It looks like [maybe this line](https://github.com/pion/webrtc/blob/7367daf2324b66290f0bdbaab1e51297de1f4989/peerconnection.go#L1093) does that but I added some logging and it's never hit in my case.

### Related issues

There are prior issues that appear to be about the same thing:

https://github.com/pion/webrtc/issues/1030
https://github.com/pion/webrtc/issues/925
https://github.com/pion/ion-sfu/issues/23

A lot of these issues were closed but they link to a page that 404s so I can't tell what code change may have addressed this. If you can point me to the right place I can try and make a PR.

**Comment by Sean-Der** [comment] 2022-05-24 03:12
Hey @matt-allan 

Thanks for the detailed bug! Pion WebRTC does support dynamic PayloadTypes, so I don't believe the issue is coming from this repo (but I have been wrong before!)

TrackLocal is an interface. I believe the issue is that pion/mediadevices is missing code like [this](https://github.com/pion/webrtc/blob/master/track_local_static.go#L60)

Debugging can you check the PayloadType [here](https://github.com/pion/mediadevices/blob/e316b309640160d84fe3e28160595a021a6a5138/track.go#L207) and see what it is ?

**Comment by Sean-Der** [comment] 2022-05-31 20:04
Hey @matt-allan

Hopefully this worked for you! Resolving for now, if you are still having issues please re-open

thanks for using Pion :)

**Closed by Sean-Der** 2022-05-31 20:04 UTC
