### ISSUE TITLE
Exchange messages using Windows environment

### ISSUE THREAD

**Issue by netwer** [pion/webrtc#195] opened 2018-10-03 20:30 UTC
Hi, we are trying to sending message using windows environment. 

We have 1 server instance run on the Windows from NAT network and other one client instance run on the Windows from NAT network on other PC. 

As the result we cant exhange messages and we cant see any errors. 

Can you help as run this solution using Windows enviroment, because is it important for us?

If you need we can gve you as information you want.

Thanks.

PS we are using this example: https://github.com/pions/webrtc/tree/master/examples/pion-to-pion

**Comment by backkem** [comment] 2018-10-04 05:16
Hi @netwer. Glad to have you use the library! Can you share the errors you are getting?
Note that WebRTC should be able to traverse NATs. However, the pion-to-pion example uses a direct HTTP connection to exchange the SDP information. This HTTP connection is not able to traverse NAT. For use-cases where both peers are behind NAT you would need to exchange the SDP over a rendezvous server, that is a server that both peers can make a direct connection to individually.
We should probably do a better job of explaining this in the example and maybe add a rendezvous example as well.

**Comment by backkem** [comment] 2018-10-04 08:01
Actually, I seem to be able to reproduce this. I'll need to find more time for testing, please stand by.

**Comment by Sean-Der** [comment] 2018-10-04 17:45
Hey @netwer can you try master please?

@backkem fixed a bug where we could get IPv6 srflx candidates back from the STUN server (and then we would fail to parse them) so you would only end up with host candidates.

**Comment by netwer** [comment] 2018-10-04 19:04
@backkem @Sean-Der Hey!
We are tried changes from master and no successful result. 
We are use the following pion scripts for testing:
1 pion
`package main

import (
	"bufio"
	"encoding/base64"
	"fmt"
	"io"
	"math/rand"
	"os"
	"time"

	"github.com/pions/webrtc"
	"github.com/pions/webrtc/pkg/datachannel"
	"github.com/pions/webrtc/pkg/ice"
)

func main() {
	/* Everything below is the pion-WebRTC API, thanks for using it! */

	// Prepare the configuration
	config := webrtc.RTCConfiguration{
		IceServers: []webrtc.RTCIceServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	}

	// Create a new RTCPeerConnection
	peerConnection, err := webrtc.New(config)
	check(err)

	// Set the handler for ICE connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnICEConnectionStateChange = func(connectionState ice.ConnectionState) {
		fmt.Printf("ICE Connection State has changed: %s\n", connectionState.String())
	}

	// Register data channel creation handling
	peerConnection.OnDataChannel = func(d *webrtc.RTCDataChannel) {
		fmt.Printf("New DataChannel %s %d\n", d.Label, d.ID)

		d.Lock()
		defer d.Unlock()

		// Register channel opening handling
		d.OnOpen = func() {
			fmt.Printf("Data channel '%s'-'%d' open. Random messages will now be sent to any connected DataChannels every 5 seconds\n", d.Label, d.ID)

			for range time.NewTicker(5 * time.Second).C {
				message := randSeq(15)
				fmt.Printf("Sending %s \n", message)

				err := d.Send(datachannel.PayloadString{Data: []byte(message)})
				check(err)
			}
		}

		// Register message handling
		d.Onmessage = func(payload datachannel.Payload) {
			switch p := payload.(type) {
			case *datachannel.PayloadString:
				fmt.Printf("Message '%s' from DataChannel '%s' payload '%s'\n", p.PayloadType().String(), d.Label, string(p.Data))
			case *datachannel.PayloadBinary:
				fmt.Printf("Message '%s' from DataChannel '%s' payload '% 02x'\n", p.PayloadType().String(), d.Label, p.Data)
			default:
				fmt.Printf("Message '%s' from DataChannel '%s' no payload \n", p.PayloadType().String(), d.Label)
			}
		}
	}


	// Wait for the offer to be pasted
	sd := mustReadStdin()

	// Set the remote SessionDescription
	offer := webrtc.RTCSessionDescription{
		Type: webrtc.RTCSdpTypeOffer,
		Sdp:  string(sd),
	}

	err = peerConnection.SetRemoteDescription(offer)
	check(err)

	// Sets the LocalDescription, and starts our UDP listeners
	answer, err := peerConnection.CreateAnswer(nil)
	check(err)

	// Get the LocalDescription and take it to base64 so we can paste in browser
	fmt.Println(base64.StdEncoding.EncodeToString([]byte(answer.Sdp)))

	// Block forever
	select {}
}

func randSeq(n int) string {
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	letters := []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
	b := make([]rune, n)
	for i := range b {
		b[i] = letters[r.Intn(len(letters))]
	}
	return string(b)
}

// check is used to panic in an error occurs.
func check(err error) {
	if err != nil {
		panic(err)
	}
}

// mustReadStdin blocks untill input is received from stdin
func mustReadStdin() string {
	reader := bufio.NewReader(os.Stdin)
	rawSd, err := reader.ReadString('\n')
	if err != io.EOF {
		check(err)
	}

	fmt.Println("")

	sd, err := base64.StdEncoding.DecodeString(rawSd)
	check(err)

	return string(sd)
}`
2 pion
`package main

import (
	"bufio"
	"encoding/base64"
	"fmt"
	"io"
	"math/rand"
	"os"
	"time"

	"github.com/pions/webrtc"
	"github.com/pions/webrtc/pkg/datachannel"
	"github.com/pions/webrtc/pkg/ice"
)

func main() {
	// Prepare the configuration
	config := webrtc.RTCConfiguration{
		IceServers: []webrtc.RTCIceServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	}

	// Create a new RTCPeerConnection
	peerConnection, err := webrtc.New(config)
	check(err)

	// Create a datachannel with label 'data'
	dataChannel, err := peerConnection.CreateDataChannel("data", nil)
	check(err)

	// Set the handler for ICE connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnICEConnectionStateChange = func(connectionState ice.ConnectionState) {
		fmt.Printf("ICE Connection State has changed: %s\n", connectionState.String())
	}

	dataChannel.Lock()

	// Register channel opening handling
	dataChannel.OnOpen = func() {
		fmt.Printf("Data channel '%s'-'%d' open. Random messages will now be sent to any connected DataChannels every 5 seconds\n", dataChannel.Label, dataChannel.ID)

		for range time.NewTicker(5 * time.Second).C {
			message := randSeq(15)
			fmt.Printf("Sending %s \n", message)

			err := dataChannel.Send(datachannel.PayloadString{Data: []byte(message)})
			check(err)
		}
	}

	// Register the Onmessage to handle incoming messages
	dataChannel.Onmessage = func(payload datachannel.Payload) {
		switch p := payload.(type) {
		case *datachannel.PayloadString:
			fmt.Printf("Message '%s' from DataChannel '%s' payload '%s'\n", p.PayloadType().String(), dataChannel.Label, string(p.Data))
		case *datachannel.PayloadBinary:
			fmt.Printf("Message '%s' from DataChannel '%s' payload '% 02x'\n", p.PayloadType().String(), dataChannel.Label, p.Data)
		default:
			fmt.Printf("Message '%s' from DataChannel '%s' no payload \n", p.PayloadType().String(), dataChannel.Label)
		}
	}

	dataChannel.Unlock()

	// Create an offer to send to the browser
	offer, err := peerConnection.CreateOffer(nil)
	check(err)

	// Output the offer in base64 so we can paste it in browser
	fmt.Println(base64.StdEncoding.EncodeToString([]byte(offer.Sdp)))

	// Exchange the offer for the answer
	//answer := mustSignalViaHTTP(offer, *addr)

	// Wait for the answer to be pasted
	sd := mustReadStdin()

	// Set the remote SessionDescription
	answer := webrtc.RTCSessionDescription{
		Type: webrtc.RTCSdpTypeAnswer,
		Sdp:  sd,
	}

	// Apply the answer as the remote description
	err = peerConnection.SetRemoteDescription(answer)
	check(err)

	// Block forever
	select {}
}

func randSeq(n int) string {
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	letters := []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
	b := make([]rune, n)
	for i := range b {
		b[i] = letters[r.Intn(len(letters))]
	}
	return string(b)
}

// check is used to panic in an error occurs.
func check(err error) {
	if err != nil {
		panic(err)
	}
}

// mustReadStdin blocks untill input is received from stdin
func mustReadStdin() string {
	reader := bufio.NewReader(os.Stdin)
	rawSd, err := reader.ReadString('\n')
	if err != io.EOF {
		check(err)
	}

	fmt.Println("")

	sd, err := base64.StdEncoding.DecodeString(rawSd)
	check(err)

	return string(sd)
}`

**Comment by backkem** [comment] 2018-10-04 19:09
Yes, I seems my fix isn't complete yet. I should have more time tomorrow evening and in the weekend for further debugging.

**Comment by netwer** [comment] 2018-10-04 19:10
Ou, thanks! We will be waiting you fix.

**Comment by backkem** [comment] 2018-10-06 20:31
Hi @netwer, I didn't try your example yet but I've fixed another bug that caused NAT traversal to fail. Do you mind trying with the new master again?

**Comment by backkem** [comment] 2018-10-08 19:20
Is all this information from the same test? The SDP from Pions 2 refers to IP 92.107.x.x but the MS Message Analyzer screenshot seems to send requests to 91.108.x.x?

The gathering of the server reflective candidates seems to work fine. This was related to the first bug I addressed. Assuming the information is not from the same test: There do seem to be binding requests sent to the reflective candidates. This was a problem in the 2nd bug I addressed. However, none of the binding requests seem to reach the other peer.

Questions:
- What does the network look like? Are both clients simply behind a their own NAT?
- Are they simple consumer grade NATs or highly restrictive enterprise NATs?
- Can you establish a WebRTC connection between browsers on these machines? (E.g.: use an example from https://webrtc.github.io/samples/)
- Can you sent the output of this test when un-commenting the following Printf statements:

https://github.com/pions/webrtc/blob/5095e199161f5ddf215703c4dd290e7e2509bddd/pkg/ice/agent.go#L405-L415

**Comment by netwer** [comment] 2018-10-09 21:06
> What does the network look like? Are both clients simply behind a their own NAT?

Both clients simply behind a their own NAT

> Are they simple consumer grade NATs or highly restrictive enterprise NATs?

Simple consumer grade NATs

> Can you establish a WebRTC connection between browsers on these machines? (E.g.: use an example from https://webrtc.github.io/samples/)

Yes, we can. We are used this example: https://www.sharedrop.io/

> Can you sent the output of this test when un-commenting the following Printf statements:

We are tried again binaries from the last our test builded (https://github.com/pions/webrtc/issues/195#issuecomment-427642188) and evething all works:)

Are computers has same configurations like 2 days ago.
What is going on here? :)
The result example:
```
Sending ungUgLvobpSOJXx
Message 'Payload Type String' from DataChannel 'data' payload 'GBeAKvkWanhhGna'
Sending xvUpDaaRPlqqLcz
Message 'Payload Type String' from DataChannel 'data' payload 'XsNVQEExWorLTTm'
Sending hvOZiCgzHpPmrOI
Message 'Payload Type String' from DataChannel 'data' payload 'BfdyAFsdveQRINo'
Sending WPRvZiIOdVunSVQ
Message 'Payload Type String' from DataChannel 'data' payload 'gLdbFnxPmTptaDJ'
Sending DcVBQHRiGxfXiEO
Message 'Payload Type String' from DataChannel 'data' payload 'KmuhqsMyIPvaLVr'
Sending JyXHYbeAHmFDlkO
```

**Comment by backkem** [comment] 2018-10-10 05:18
Interesting, I've seen some instability in my testing as well. After the DTLS port and transport refactor we'll work on dialing in the reliability.

**Comment by Sean-Der** [comment] 2018-12-20 08:41
Hey @netwer 

We recently added IPv6, refactored ICE and are 100% Go (dropped OpenSSL dependency) If you get a chance would you mind testing again? No rush though! I would love to make sure everything works before we cut a new release, sorry for the delay we got wrapped up working on a lot of cool stuff :)

Thanks again for using pion-WebRTC

**Comment by netwer** [comment] 2018-12-22 20:42
Hi @Sean-Der.
Thanky for your answer.

We are took the last version. The build was ok, but when we try to execute "answer" and "offer" projects we got the following errors:

**offer:**
```
%GOPATH%\src\github.com\pions\webrtc\examples\pion-to-pion\offer>offer.exe
could not allocate udp6 stun:stun.l.google.com:19302: Failed to create STUN client: dial udp6: address stun.l.google.com: no suitable address found
panic: Post http://:50000: dial tcp :50000: connectex: No connection could be made because the target machine actively refused it.

goroutine 1 [running]:
github.com/pions/webrtc/examples/util.Check(...)
        %GOPATH%/src/github.com/pions/webrtc/examples/util/util.go:27
main.mustSignalViaHTTP(0x1, 0xc0001c3800, 0x7b9, 0xc00007d320, 0x7306cb, 0x6, 0x0, 0x0, 0x0, 0x0)
        %GOPATH%/src/github.com/pions/webrtc/examples/pion-to-pion/offer/main.go:93 +0x385
main.main()
        %GOPATH%/src/github.com/pions/webrtc/examples/pion-to-pion/offer/main.go:76 +0x309
```

**answer:**
```
%GOPATH%\src\github.com\pions\webrtc\examples\pion-to-pion\answer>answer.exe
could not allocate udp6 stun:stun.l.google.com:19302: Failed to create STUN client: dial udp6: address stun.l.google.com: no suitable address found
Listening on :50000
```

**Comment by netwer** [comment] 2018-12-23 09:50
Hi @Sean-Der 

yesterday we made a mistake in the order of launching applications

today checked in the correct order and locally everything works,
however, the error about stun is present, but the program does not fall
Also when we exchange sdp strings by hands beetween answer and offer, nothing works

**Comment by Sean-Der** [comment] 2018-12-23 16:40
The STUN error is non-fatal, we don't have leveled logging yet. We have someone working on it [here](https://github.com/pions/webrtc/pull/236) though! Sorry for the white noise.

If you exchange SDP strings manually on the same machine does it work? Just to confirm that the application works, and ruling out any bugs there.

If that works you might have a firewall/NAT that doesn't allow UDP traffic. Currently we don't support TURN (but is our next big project after this release) For debugging I usually do `tcpdump -i any udp and inbound` and it will show inbound ICE traffic. Trying doing that on both sides and make sure they are both getting traffic.

**Comment by netwer** [comment] 2018-12-23 18:59
@Sean-Der 

> If you exchange SDP strings manually on the same machine does it work?

yes, we checked on the same machine it works

> If that works you might have a firewall/NAT that doesn't allow UDP traffic.

yes, we have NAT, but UPD traffic allowed. We checked it by wireshark.

Also, we created [electron](https://electronjs.org/) app and check webrtc in this app and it works.

**Comment by netwer** [comment] 2018-12-24 21:51
Hi, @Sean-Der

1) In Electron application we are using only STUN protocol, without TURN.
2) Both PCs gets and seds UDP datagram. We do two dumps from two differ computers. As you ask, we send it to your email.
3) We share with you our simple demo applications, based on pions and electron. Sorry, that electron example just has two files. Other files is specific of our real application.

**Comment by Sean-Der** [comment] 2018-12-25 06:31
Hey @netwer got your email and responded!

To anyone following along we will fix this offline, I will update+close this ticket when we fix the issue.

**Comment by netwer** [comment] 2018-12-26 22:06
Hi @Sean-Der 
We are sent reply to your email.

**Comment by Sean-Der** [comment] 2019-06-25 08:36
@netwer 

Hey sorry for missing this, finally getting around to triaging issues https://pion.ly/knowledge-base/pion-internals/contributing/

I sent you an email, but we fixed our Peer Reflexive NAT issue since we talked. We also added TURN support, so if you still have issues that should help!

If there is anything I can do please grab me via email or [Slack](https://pion.ly/slack) and would love to get you all fixed up.

**Closed by Sean-Der** 2019-06-25 08:36 UTC
Labels: backlog, bug
