### ISSUE TITLE
AVFoundation Bind/AVFoundation Bind.h file not found

### ISSUE THREAD

**Issue by MunDeuksoo** [pion/webrtc#1643] opened 2021-01-20 00:51 UTC
### Your environment.
  - Version: v3
  - Browser: ION-SFU 
  - Other Information -MACOS

### What did you expect?
I was expected to run camera on mac.
### What happened?
I was failed to run 'https://gabrieltanner.org/blog/broadcasting-ion-sfu' example source and it message 'AVFoundation Bind/AVFoundation Bind.h file not found'

**Comment by Sean-Der** [comment] 2021-01-20 05:33
Hey @MunDeuksoo 

This seems to be a dupe of https://github.com/pion/mediadevices/issues/290. Please re-open if I am wrong. 

thanks!

**Closed by Sean-Der** 2021-01-20 05:33 UTC
