### ISSUE TITLE
 Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

### ISSUE THREAD

**Issue by VOIDTOR** [pion/webrtc#1714] opened 2021-03-18 13:15 UTC
Hi, pion is a awesome sdk  of webrtc,  I want to use it to start a sfu application. now i need some  help .
when I try to start  simucast sfu ,  Chrome  give me a error message when sfu‘s sdp (answer)  adding to the client side peerconneciton.

"Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer."

can some one  have a look at this ? thanks alot.
**here is the "answer"** 
```
v=0
o=- 6341442797458035898 1616071687 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 99:FA:D0:22:83:20:44:1A:A3:58:19:89:5A:BE:D1:E2:95:6C:2C:42:60:6B:02:4D:DB:E3:12:E4:89:2C:B6:B1
a=group:BUNDLE 0 1
m=audio 9 UDP/TLS/RTP/SAVPF 111 9 0 8
c=IN IP4 0.0.0.0
a=setup:active
a=mid:0
a=ice-ufrag:uJXaqnASuiorWRoL
a=ice-pwd:UaMmRVRjrNhqfuEbxDyPuEeJdOSCDtQJ
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp-fb:111 transport-cc 
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=recvonly
m=video 9 UDP/TLS/RTP/SAVPF 96 98 102 127 125 108 123
c=IN IP4 0.0.0.0
a=setup:active
a=mid:1
a=ice-ufrag:uJXaqnASuiorWRoL
a=ice-pwd:UaMmRVRjrNhqfuEbxDyPuEeJdOSCDtQJ
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb 
a=rtcp-fb:96 transport-cc 
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack 
a=rtcp-fb:96 nack pli
a=rtpmap:98 VP9/90000
a=fmtp:98 profile-id=0
a=rtcp-fb:98 goog-remb 
a=rtcp-fb:98 transport-cc 
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack 
a=rtcp-fb:98 nack pli
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtcp-fb:102 goog-remb 
a=rtcp-fb:102 transport-cc 
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack 
a=rtcp-fb:102 nack pli
a=rtpmap:127 H264/90000
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtcp-fb:127 goog-remb 
a=rtcp-fb:127 transport-cc 
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack 
a=rtcp-fb:127 nack pli
a=rtpmap:125 H264/90000
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:125 goog-remb 
a=rtcp-fb:125 transport-cc 
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack 
a=rtcp-fb:125 nack pli
a=rtpmap:108 H264/90000
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtcp-fb:108 goog-remb 
a=rtcp-fb:108 transport-cc 
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack 
a=rtcp-fb:108 nack pli
a=rtpmap:123 ulpfec/90000
a=rid:q recv
a=rid:f recv
a=rid:h recv
a=simulcast:recv q;f;h
a=recvonly
```

**And here is the offer:**

```
v=0
o=- 4067546914296565504 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:KFUb
a=ice-pwd:w1ypLA8Se7LpRRfupGVJfU0C
a=ice-options:trickle
a=fingerprint:sha-256 7E:F4:8E:B6:23:62:48:BB:85:16:53:95:92:74:23:FA:E9:4C:1D:A7:5C:DC:CC:E0:B9:77:D5:38:CF:4E:95:93
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:- b0102ab2-349f-4489-a3f3-a3f6f5548932
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:941699097 cname:eYPJgrHfSX6Pa/uH
a=ssrc:941699097 msid:- b0102ab2-349f-4489-a3f3-a3f6f5548932
a=ssrc:941699097 mslabel:-
a=ssrc:941699097 label:b0102ab2-349f-4489-a3f3-a3f6f5548932
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 120 127 119 125 107 108 109 124 118 123
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:KFUb
a=ice-pwd:w1ypLA8Se7LpRRfupGVJfU0C
a=ice-options:trickle
a=fingerprint:sha-256 7E:F4:8E:B6:23:62:48:BB:85:16:53:95:92:74:23:FA:E9:4C:1D:A7:5C:DC:CC:E0:B9:77:D5:38:CF:4E:95:93
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:- b68febbe-90c8-4a4d-b817-e837d18791b3
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 red/90000
a=rtpmap:118 rtx/90000
a=fmtp:118 apt=124
a=rtpmap:123 ulpfec/90000
a=rid:f send
a=rid:h send
a=rid:q send
a=simulcast:send f;h;q
```

**Comment by Sean-Der** [comment] 2021-08-25 14:27
Hey @VOIDTOR 

I am not able to reproduce this. The two SessionDescriptions each have 2 media sections audio+video (so they look right to me)

do you have the code that threw this error still?

thanks!

**Comment by Sean-Der** [comment] 2021-09-06 02:06
I am going to close this for now. If you are interested in addressing this @VOIDTOR happy to chat here or on [Slack](https://pion.ly/slack)

**Closed by Sean-Der** 2021-09-06 02:06 UTC

**Comment by KnechtNoobrecht** [comment] 2024-02-07 02:16
Hi, little late to the party, but i am having the same problem. Offer and answer look right in my case, too. Let me know if you're still interested in addressing this.
