### ISSUE TITLE
v2 not found

### ISSUE THREAD

**Issue by DilsMatchanov** [pion/webrtc#683] opened 2019-05-22 08:21 UTC
Can't ```go build``` sfu-ws because version 2 is not found.

```
broadcast_data.go:6:2: cannot find package "github.com/pion/webrtc/v2" in any of:
	/usr/lib/go-1.10/src/github.com/pion/webrtc/v2 (from $GOROOT)
	/home/user/go/src/github.com/pion/webrtc/v2 (from $GOPATH)
```

**Comment by ernado** [comment] 2019-05-22 08:57
Hello! We are using [Go Modules](https://github.com/golang/go/wiki/Modules), so minimal supported version is go1.11, so sorry :(

Can you please try to use go with modules support, e.g. go1.12?
The installation instructions are here: https://golang.org/doc/install

**Comment by Demuzx** [comment] 2019-05-22 09:22
> Can't `go build` sfu-ws because version 2 is not found.
> 
> ```
> broadcast_data.go:6:2: cannot find package "github.com/pion/webrtc/v2" in any of:
> 	/usr/lib/go-1.10/src/github.com/pion/webrtc/v2 (from $GOROOT)
> 	/home/user/go/src/github.com/pion/webrtc/v2 (from $GOPATH)
> ```

Same error:
Windows 10
go version go1.12.1 windows/amd64

**Comment by Demuzx** [comment] 2019-05-22 10:11
![213123](https://user-images.githubusercontent.com/30521627/58166673-c8176280-7ca3-11e9-80cd-3c29bc31673b.png)

**Comment by ernado** [comment] 2019-05-22 10:14
@Demuzx 
Please go to Settings -> Go -> Go modules (vgo) and enable it like that:
![image](https://user-images.githubusercontent.com/866677/58166784-3dc70280-7c93-11e9-9f12-2fcca935909f.png)

Or just move your code outside of GOPATH.
Or set `GO111MODULE` environment variable to `on` manually, example for linux:
```bash
$ export GO111MODULE=on 
```

**Comment by Demuzx** [comment] 2019-05-22 12:12
> @Demuzx
> Please go to Settings -> Go -> Go modules (vgo) and enable it like that:
> ![image](https://user-images.githubusercontent.com/866677/58166784-3dc70280-7c93-11e9-9f12-2fcca935909f.png)
> 
> Or just move your code outside of GOPATH.
> Or set `GO111MODULE` environment variable to `on` manually, example for linux:
> 
> ```shell
> $ export GO111MODULE=on 
> ```

Project builds and now normally run. But now code look like this...

![324234](https://user-images.githubusercontent.com/30521627/58173419-c2764880-7cb4-11e9-9fc3-a9a7a9ad4da1.png)

**Comment by ernado** [comment] 2019-05-22 13:01
@Demuzx try File -> Invalidate Caches / Restart.
Also try Ctrl+Enter on those red imports, maybe goland will fix it for you.

**Comment by Sean-Der** [comment] 2019-05-22 21:20
Hey @DilsMatchanov 
Sorry this hit you, thanks @ernado for helping out!

If anyone is interested we have https://github.com/pion/webrtc/issues/633 which is for updating the documentation around modules being required. I am going to close this as a dupe of that (but feel free to re-open if I am missing anything)

thanks for using Pion :)

**Closed by Sean-Der** 2019-05-22 21:20 UTC
