### ISSUE TITLE
Q: Simple setup for peers in local-only network?

### ISSUE THREAD

**Issue by jurisevo** [pion/webrtc#2275] opened 2022-07-08 10:57 UTC
Hi,

I'm new to both WebRTC and Pion and doing my first steps trying to understand protocol from the ground up. I think I've found a reasonable starting point to dive in, namely `examples/pion-to-pion` from the GH repo.

Given that protocol is rather complicated, I was thinking starting simple, with 2 peers located in local network. Reachable without any intermediate hops. Another point was to make this network disconnected from Internet to reduce the noise of needing external STUN servers (as per my understanding).

Now, what I did is basically created a Linux network namespace with only a loopback `lo` network available. And am trying to run both `answer` and `offer` programs. Unfortunately I cannot seem to make them connect.

Any hints on what modifications I need to do?

This is what I get with tracing enabled from `answer` program:

```
[root@p15s answer]# PION_LOG_TRACE=all ./answer
pc INFO: 2022/07/08 13:32:33 signaling state changed to have-remote-offer
ice TRACE: 13:32:33.691767 agent.go:571: Set selected candidate pair: 
ice DEBUG: 13:32:33.691992 agent.go:457: Started agent: isControlling? false, remoteUfrag: "qFdMLkEugNEcnThj", remotePwd: "PrNDBSYGwodszJfXRWDTuWZMABakIBek"
ice INFO: 2022/07/08 13:32:33 Setting new connection state: Checking
pc INFO: 2022/07/08 13:32:33 ICE connection state changed: checking
ice TRACE: 13:32:33.692228 agent.go:599: pinging all candidates
ice WARNING: 2022/07/08 13:32:33 pingAllCandidates called with no candidate pairs. Connection is not possible yet.
pc INFO: 2022/07/08 13:32:33 signaling state changed to stable
ice WARNING: 2022/07/08 13:32:33 failed to resolve stun host: stun.l.google.com:19302: lookup stun.l.google.com: Temporary failure in name resolution
ice WARNING: 2022/07/08 13:32:33 failed to resolve stun host: stun.l.google.com:19302: lookup stun.l.google.com: Temporary failure in name resolution
ice TRACE: 13:32:33.893316 agent.go:599: pinging all candidates
ice WARNING: 2022/07/08 13:32:33 pingAllCandidates called with no candidate pairs. Connection is not possible yet.
ice TRACE: 13:32:34.094530 agent.go:599: pinging all candidates
ice WARNING: 2022/07/08 13:32:34 pingAllCandidates called with no candidate pairs. Connection is not possible yet.
ice TRACE: 13:32:34.295095 agent.go:599: pinging all candidates
```

If this is not appropriate place to ask such question, please, feel free to redirect me accordingly (:fingers_crossed: - not slack).

**Comment by Sean-Der** [comment] 2022-07-10 19:53
Hi @jurisevo 

The issue is that [github.com/pion/ice](https://github.com/pion/ice) ignores loopback when enumerating the possible interfaces. That is done [here](https://github.com/pion/ice/blob/e5242f621c02fc62fe1dee95ad1a503266a92b0b/util.go#L178-L180) and [here](https://github.com/pion/ice/blob/e5242f621c02fc62fe1dee95ad1a503266a92b0b/util.go#L157-L159)

I think by default this is the right behavior. The default connection flow would take on lots of extra pointless traffic. However I think we could make this a [AgentConfig](https://github.com/pion/ice/blob/master/agent_config.go#L52) entry. I would add a `GatherLoopback` bool. 

I am going to close this issue for now. I don't believe that people are blocked by not having this feature. If they are running in a 'loopback only environment' and find this issue they will probably just add another interface. However, if you are interested in implementing (could be a fun project) would love to help :)

**Closed by Sean-Der** 2022-07-10 19:53 UTC

**Comment by jurisevo** [comment] 2022-07-11 05:08
@Sean-Der Than you for detailed explanation! Current behaviour does make sense, I will build up my setup with more realistic network interfaces.
