### ISSUE TITLE
Occasional panic on AddICECandidate

### ISSUE THREAD

**Issue by edwinhayes** [pion/webrtc#1234] opened 2020-06-02 03:37 UTC
Perhaps 1% of the time, when I get an ICE candidate from my signalling server and try to add it, Pion panics:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1f0 pc=0xc4d392]

goroutine 2921 [running]:
github.com/pion/ice.(*Agent).ok(0x0, 0x80, 0x80)
        /home/ehayes/go/pkg/mod/github.com/pion/ice@v0.7.10/agent.go:166 +0x22
github.com/pion/ice.(*Agent).run(0x0, 0xc0009849d8, 0xc00025a413, 0xb)
        /home/ehayes/go/pkg/mod/github.com/pion/ice@v0.7.10/agent.go:183 +0x40
github.com/pion/ice.(*Agent).AddRemoteCandidate(0x0, 0x12041c0, 0xc0008af9a0, 0x9, 0x2001eff)
        /home/ehayes/go/pkg/mod/github.com/pion/ice@v0.7.10/agent.go:785 +0x1ee
github.com/pion/webrtc/v2.(*ICETransport).AddRemoteCandidate(0xc000208800, 0x0, 0x0, 0xc00025a3fa, 0x9, 0x2001eff, 0xc00025a413, 0xb, 0x1, 0xe7e1, ...)
        /home/ehayes/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/icetransport.go:238 +0x10f
github.com/pion/webrtc/v2.(*PeerConnection).AddICECandidate(0xc0001fa000, 0xc00025a3f0, 0x89, 0x0, 0x0, 0x0, 0x0, 0x8, 0x0)
        /home/ehayes/go/pkg/mod/github.com/pion/webrtc/v2@v2.2.4/peerconnection.go:1026 +0x1ef
```

**Comment by Sean-Der** [comment] 2020-06-02 04:03
Hey @edwinhayes 

I believe we fixed this https://github.com/pion/ice/commit/88b716cb3bcd2dd54f3f022b46f4212b9746e555

Mind updating to the newest version and see if that helps? thanks!

**Comment by edwinhayes** [comment] 2020-06-02 05:35
@Sean-Der - certainly; I will update my build tomorrow - however given the infrequent nature of the panic, it will potentially be a while before I can be sure it's gone.

Thanks!

**Comment by edwinhayes** [comment] 2020-06-03 00:29
@Sean-Der - I can't updated to the newest version (v2.2.14): between v2.2.10 and v2.2.11, something breaks for me.  On v2.2.11, I get an ICE connection, but then no frames seem to come through.  Can you tell me what changed between these two versions so that I can track down the issue (related - is there some place that you have release notes recorded)?

**Comment by Sean-Der** [comment] 2020-06-03 02:59
Oof that is no good :/ We had two commits

a2c7665fade3953a41e7ca6d83cc2831e7c995c3
b66c3c4903dfd295bb5d240eb947f48f9a8a9af9

Can you open `chrome://webrtc-internals` and see if you have any video flowing? Does ICEConnectionState go to connected/completed on both sides? Are you using Pion to send or receive video? 

I am not sure exactly what the issue is, but would love to help you debug and get this fixed.

thanks

**Comment by edwinhayes** [comment] 2020-06-03 08:51
This is Pion doing the sending from a native Go app; the receiving end is JS in Chrome.  WebRTC internals looks like zero packets received, but I'm putting 2000kbps into `WriteSample()` onto sending side.  ICE connection state is connected on both ends.

**Comment by Sean-Der** [comment] 2020-06-03 09:02
Can you confirm that

Can you check that things are actually sending [here](https://github.com/pion/webrtc/blob/master/track.go#L160) it is possible the RTPSender hasn't gone to started yet (not sure why)

It doesn't sound like a connectivity issue, but signaling/media only.

Also double check that your SDPs haven't changed between versions. Make sure they have the same amount of media sections, and the directions haven't changed! That could be a good lead.

**Comment by edwinhayes** [comment] 2020-06-04 04:27
I will have to get a debugger set up to see if we get to that line.

Checked SDPs though; diffing the before and after doesn't see to show any material differences (other than SSRCs, ports, etc) from v10 to v14.

**Comment by Sean-Der** [comment] 2020-06-04 04:34
Are you able to add a `fmt.Println` ? Any chance of a minimal reproduce? If you want to email me directly happy to help debug 1:1 sometime. sean @ siobud.com

I really am excited when people use Pion, and getting bug reports is super important to me. I don't want a bug to stop you from upgrading :(

**Comment by edwinhayes** [comment] 2020-06-04 05:00
Yeah, if necessary, but at the moment, our build system is just fetching the package directly from Github, I'm not building manually, so I'll just have to figure out what the least-effort path is.  Have quite a few other demands on my time at the moment, so am trying to fit this in where possible.  Thanks for the offer though, that would be great!

**Comment by Sean-Der** [comment] 2020-06-16 07:28
Hey @edwinhayes 

Any luck on this? I don't want to close this out without getting your issue fixed! I just don't have anything actionable atm

thanks!

**Comment by edwinhayes** [comment] 2020-06-16 08:40
Hi @Sean-Der - Sorry, I have not been able to devote any time to this in the last week; I hope to either do this myself, or have someone on my team, pick this up towards the end of the week.  It is still definitely important for me though, so will get some more info to you as soon as possible.

**Comment by Sean-Der** [comment] 2020-06-16 08:53
If Pion is answering make sure you `AddTrack` `AddTransceiver` before `SetRemoteDescription` and `CreateAnswer` (I saw this bite someone recently when upgrading)

But I am here to help! If you (or someone else on the team) wants to jump on a call happy to help debug 1:1 (for free). I just am worried there is a bug.

thanks

**Comment by edwinhayes** [comment] 2020-07-08 03:43
Sorry, this has not been forgotten, just have not been able to get someone onto it yet.

> If Pion is answering make sure you AddTrack AddTransceiver before SetRemoteDescription and CreateAnswer (I saw this bite someone recently when upgrading)

This was previously an issue for us, but we'd already fixed it, so it's not the cause of this issue.

**Comment by edwinhayes** [comment] 2020-08-24 22:01
Hi @Sean-Der,

This had kind of dropped off my radar, until someone (probably me) accidentally upgraded the Pion version we were pinned to, and suddenly video stopped working again.  So now I'm inclined to actually try to figure this out...

Seems like the issue is that, in `WriteRTP()`, there are no items in the list `t.activeSenders`.  And that is empty because `Send()` in `rtpsender.go` never gets called.  That seems like it's because `startRTPSenders()` and its parent `startRTP()` doesn't get called.  Which definitely looks like it's related to the changes to `peerconnection.go`in b66c3c4.  But I'm not really sure what was actually being done there.

**Comment by edwinhayes** [comment] 2020-08-24 22:15
To a cursory glance, it looks like all the calls to `startRTP()` are behind a conditional `if weOffer`, which is evaluating to false.  I'm not exactly sure what that is supposed to do, but in my case, Pion is answering, rather than offering; I don't really see anywhere where the RTP senders are started in the answering case?

**Comment by Sean-Der** [comment] 2020-08-24 23:39
@edwinhayes 

If you are answering it should be called [here](https://github.com/pion/webrtc/blob/master/peerconnection.go#L887-L891)

Does that get fired? When it goes into `startRTPSenders` do the `if` checks stop it there?

**Comment by edwinhayes** [comment] 2020-08-25 03:30
@Sean-Der .

Sigh...  I have a different thing to report instead: did you know that prior to version 2.2.11, connections would still work normally, even if someone had accidentally and unhelpfully _commented out SetLocalDescription()_...  :-(

So... ah... Yeah apparently for some period of time, we just haven't been setting the local description.  The latest version works now...  Hopefully that means the original issue I noted in this thread is now also resolved.

**Comment by Sean-Der** [comment] 2020-08-31 21:45
nice! Glad to her this is fixed :D sorry missed this been busy with the book 

So I *think* there is nothing we can do here (since this is on the answerer side) but please re-open if I am wrong

**Closed by Sean-Der** 2020-08-31 21:45 UTC
