### ISSUE TITLE
Deadlock while peerConnection.GetStats()

### ISSUE THREAD

**Issue by Filatoff73** [pion/webrtc#873] opened 2019-10-10 07:38 UTC
### Your environment.
  - Version: *2.1.6*
  - windows 10
  
I am try to get GetStats() from peerConnection. My project was based on the webrtc/examples/save-to-disk. But the function GetStats() freezes. During debugging, I found that this part of the code hangs:
if pc.sctpTransport! = nil {
pc.sctpTransport.collectStats (statsCollector)
}
The mutex in "func (r *SCTPTransport) collectStats" r.lock.Lock () is trying to lock, but this does not work, since it was previously locked in the "func (r * SCTPTransport) Start (remoteCaps SCTPCapabilities) error" method.

**Comment by Sean-Der** [comment] 2019-10-10 07:46
Good catch!  I will check this out now and see what I can figure out :)

Thanks for using Pion!

**Comment by Sean-Der** [comment] 2019-10-10 08:28
@Filatoff73 as a temporary fix I would create a single data channel on the offering side.

The issue is that we are starting the SCTP subsystem even if the other side doesn't support, and we hang forever. I will be able to fix this in the next 72 hours, thanks for reporting!

**Comment by Filatoff73** [comment] 2019-10-10 09:09
@Sean-Der thanks for the help!

**Comment by Sean-Der** [comment] 2019-11-21 20:24
Fixed! This was fixed by ce4071b96c6c67e55a65ef23f878d571c4fe1216

Sorry for the delay and really appreciate you reporting this @Filatoff73 if anything else comes up always here to help!

**Closed by Sean-Der** 2019-11-21 20:24 UTC
Labels: triaged
