### ISSUE TITLE
Opus recorded file is corrupted

### ISSUE THREAD

**Issue by Demuzx** [pion/webrtc#697] opened 2019-05-31 08:35 UTC
I've record audio opus file like in your example, but record only shows it length and not played.

How can i fix opus record file?

Piece of code, it uses your (i *OpusWriter) WriteRTP(packet *rtp.Packet) funcrion.

A similar video recording function works normally, but playback speed is corrupted (i *IVFWriter) WriteRTP(packet *rtp.Packet),

**Comment by Sean-Der** [comment] 2019-05-31 08:37
If you use the save-to-disk example does it not work?

Opus isn't playable in all players currently, I would try ffmpeg if possible until https://github.com/pion/webrtc/issues/485 is closed

**Comment by Demuzx** [comment] 2019-05-31 08:42
> If you use the save-to-disk example does it not work?
> 
> Opus isn't playable in all players currently, I would try ffmpeg if possible until #485 is closed

```
ffmpeg can't convert or open file, output in console is:

ffmpeg -i input.opus output.mp3
ffmpeg version N-93945-g02333fe394 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 28.100 / 56. 28.100
  libavcodec     58. 52.102 / 58. 52.102
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 54.101 /  7. 54.101
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
[ogg @ 00000234632a8740] Packet processing failed: Invalid data found when processing input
    Last message repeated 1 times
Input #0, ogg, from 'input.opus':
  Duration: 00:03:28.88, bitrate: 11 kb/s
    Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
Stream mapping:
  Stream #0:0 -> #0:0 (opus (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[ogg @ 00000234632a8740] Packet processing failed: Invalid data found when processing input
input.opus: Invalid data found when processing input
Output #0, mp3, to 'output.mp3':
  Metadata:
    TSSE            : Lavf58.27.103
    Stream #0:0: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavc58.52.102 libmp3lame
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
```

**Comment by Sean-Der** [comment] 2019-05-31 08:52
You created the `input.opus` via the `save-to-disk` example?

I am not able to reproduce unfortunately, so not sure how to move forward .

I noticed we do hardcode some values https://github.com/pion/webrtc/blob/master/examples/save-to-disk/main.go#L71 if you check the SDP does this match up with what you are sending?

Also just to make sure https://github.com/pion/webrtc/blob/master/examples/save-to-disk/main.go#L97 doesn't fire multiple times? It shouldn't be possible, but want to make sure you aren't sending audio multiple times.

**Comment by Demuzx** [comment] 2019-05-31 09:31
> You created the `input.opus` via the `save-to-disk` example?

Yes


> I noticed we do hardcode some values https://github.com/pion/webrtc/blob/master/examples/save-to-disk/main.go#L71 if you check the SDP does this match up with what you are sending?

I've tried your example save-to-disk again. SDP opus params match with what i'm sending. 48khz, 2ch


> Also just to make sure https://github.com/pion/webrtc/blob/master/examples/save-to-disk/main.go#L97 doesn't fire multiple times? It shouldn't be possible, but want to make sure you aren't sending audio multiple times.

Audio sends one time. (((

**Comment by Stanly1995** [comment] 2019-07-09 08:55
I have the same problem.

**Comment by Stanly1995** [comment] 2019-07-09 09:24
You have to fix bug in func (i *OpusWriter) WriteRTP(packet *rtp.Packet) error
opusPacket.Payload[0:] => packet.Payload[0:] 
or change opusPacket.Unmarshal and put packet,Payload to opusPacket.Payload in this func.

After that I was able to open it in the browser.

**Comment by Sean-Der** [comment] 2019-07-09 09:34
Fantastic find @Stanly1995! Would you be up for opening a PR :) I am traveling but I can get that merged in ~12 hours. 

https://pion.ly/knowledge-base/pion-internals/contributing/

**Comment by Stanly1995** [comment] 2019-07-09 09:45
I think I can do that today.

**Comment by Stanly1995** [comment] 2019-07-09 11:15
I saw that the master does not have this bug, but gomod pulls up the rtp tag 1.1.2 with this problem.

**Comment by Sean-Der** [comment] 2019-07-09 16:55
Hey @Stanly1995 

I opened a PR to bump `pion/rtp` thanks for catching that!

**Closed** 2019-07-09 22:31 UTC
