### ISSUE TITLE
Unable to work when behind ipv6

### ISSUE THREAD

**Issue by rushib1** [pion/webrtc#810] opened 2019-08-31 11:27 UTC
### Your environment.
  - Version: go version go1.12.8 linux/amd64; github.com/pion/webrtc/v2 v2.1.2
  - Browser: not using browser. Using flutter-webrtc
  - the server is behind ipv4 only internet. The mobile is behind jio cellular network which support both ipv4 and ipv6.

### What did you do?

I am trying to stream a voice from external device from pion server to mobile.

### What did you expect?
I was expecting it to connect and make a IceConnectionState to connected

### What happened?
The connection always fails.
Connection State has changed checking 
Connection State has changed failed 

It works when both devices are behind ipv4 or both are behind cellular network.

This is the sdp from server:
[https://pastebin.com/1gbebTGF](https://pastebin.com/1gbebTGF)
This is the sdp from mobile cellular 4g (answer):
[https://pastebin.com/u8KL2cEZ](https://pastebin.com/u8KL2cEZ)

**Comment by rwrz** [comment] 2019-12-20 18:10
Hey @rushib1 , to make it work, you need an IPv6 STUN/TURN server... I had the same issue and could only implement this on AWS. Tried on GoogleCloud, but their support to IPv6 sux.

- create a machine with IPv6 address, make sure you have both, IPv4 and IPv6 address ([how to on AWS](https://docs.aws.amazon.com/vpc/latest/userguide/get-started-ipv6.html))
- start pion turn server or coturn, both works

Just a little more information, the problem with IPv6 exists because an "only ipv6" connection can't connect to an IPv4. So, using IPv6 on an IPv4 stun server, you will never receive ICE Candidates, because you can't connect to it. And even if you have an IPv6 STUN server, other users will be using IPv4, so you can't connect to their candidates.
So, you will have better success rates using a STUN/TURN with IPv6 and IPv4 support.

Hope I could help you.

**Comment by Sean-Der** [comment] 2020-10-07 17:14
Closing for https://github.com/pion/webrtc/issues/1315

**Closed by Sean-Der** 2020-10-07 17:14 UTC

**Comment by jech** [comment] 2021-01-16 00:22
This is not a duplicate of #1315 — the latter is Pion reacting correctly to malformed SDP.  There is no evidence of malformed SDP in this report.
