### ISSUE TITLE
Seg fault on sctp channel following rude ICE disconnect

### ISSUE THREAD

**Issue by sipsorcery** [pion/webrtc#1338] opened 2020-07-17 13:33 UTC
While running the `data-channels` example if the remote peer disappears a seg fault occurs.

````
Sending 'jUzStEYEqkwJqSD'
ICE Connection State has changed: disconnected
Sending 'rXeAjeHKTgDiEHs'
Sending 'sSokZiKxeHveyYv'
Sending 'KJnwQOHdhjAaVrR'
Sending 'YTkHgHgGaGyayLB'
Sending 'sxMasdPdVUfAnXk'
ICE Connection State has changed: failed
Sending 'QqKwKSKbNUeYTKU'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x6d73b8]

goroutine 96 [running]:
github.com/pion/ice/v2.(*candidateBase).writeTo(0xc00019c280, 0xc000223680, 0x51, 0x60, 0x941560, 0xc0000c17c0, 0x0, 0x0, 0x0)
        /home/aaron/go/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/candidate_base.go:185 +0x48
github.com/pion/ice/v2.(*candidatePair).Write(...)
        /home/aaron/go/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/candidatepair.go:86
github.com/pion/ice/v2.(*Conn).Write(0xc0002f68e0, 0xc000223680, 0x51, 0x60, 0x4587b0, 0xc000064c50, 0xc000064c58)
        /home/aaron/go/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/transport.go:105 +0x152
github.com/pion/webrtc/v3/internal/mux.(*Endpoint).Write(0xc000302350, 0xc000223680, 0x51, 0x60, 0xc0002f2480, 0xc0000f52c0, 0xc0002236e0)
        /home/aaron/go/src/github.com/pion/webrtc/internal/mux/endpoint.go:41 +0x59
github.com/pion/dtls/v2/internal/net/connctx.(*connCtx).Write(0xc0002f2480, 0x93bec0, 0xc0002f8e60, 0xc000223680, 0x51, 0x60, 0x0, 0x0, 0x0)
        /home/aaron/go/pkg/mod/github.com/pion/dtls/v2@v2.0.1/internal/net/connctx/connctx.go:121 +0x1e4
github.com/pion/dtls/v2.(*Conn).writePackets(0xc000332000, 0x93bec0, 0xc0002f8e60, 0xc000064ec0, 0x1, 0x1, 0x0, 0x0)
        /home/aaron/go/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:396 +0x8c3
github.com/pion/dtls/v2.(*Conn).Write(0xc000332000, 0xc00002c3f0, 0x2c, 0x30, 0x1, 0x0, 0x0)
        /home/aaron/go/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:316 +0x21a
github.com/pion/sctp.(*Association).writeLoop(0xc000392000)
        /home/aaron/go/pkg/mod/github.com/pion/sctp@v1.7.6/association.go:445 +0x2f9
created by github.com/pion/sctp.(*Association).init
        /home/aaron/go/pkg/mod/github.com/pion/sctp@v1.7.6/association.go:299 +0xcf
exit status 2
````

**Comment by Sean-Der** [comment] 2020-07-17 17:29
Oof really sorry about that :(

Master had a crash caused by ICE fixed in https://github.com/pion/ice/issues/247 I updated pion/webrtc here https://github.com/pion/webrtc/commit/a2475c19524d4dd6a7d6d2a22e242012c243850f

If you are still hitting this after updating I am here to jump in and debug :)

**Closed by Sean-Der** 2020-07-17 17:29 UTC

**Comment by sipsorcery** [comment] 2020-07-17 18:09
No need to be sorry, I'm more than happy to have some command line examples to test with.

Will pull down the latest code and test again.
