### ISSUE TITLE
DataChannels cannot send too many message at the same time.

### ISSUE THREAD

**Issue by lamhai1401** [pion/webrtc#2072] opened 2022-01-04 05:32 UTC
### Your environment.
  - Version:  PionWebrtc v3.1.11
  - Browser: Chrome Newest Version
  - Other Information - Using `simulcast` feature, pion webrtc is a server and chrome is a client.

### What did you do?
I'm trying to create two peer for each client, one peer is `data channel`and the other is `media peer` (for send/ receive many track data). Like img above:

<img width="247" alt="Screen Shot 2022-01-04 at 12 16 36" src="https://user-images.githubusercontent.com/31619361/148012703-ef0b3042-0d5d-4b8d-b98f-ea355ee76ced.png">

Each Client create `dc` (datachannel) first via `websocket` and use it for create `media peer` (send/receive sdp - candidate like signal). 

I have ack for each msg (always less than 65kb) send via `dc` .

### What did you expect?
All of msg was sent by `dc` should success.

### What happened?
To add more track for each `media peer` when i have more than 5 Client, all of them need re-handshake with `Pion server` at the same time. SDP/Candidate was sent by `Pion` will missing ack randomly (i was checked in Chrome and did not receive the missing msg, so their did not send ack back) then `media peer` state is failed sometime.

I guest the `dc` peer cannot send/receive too many msg at the same time or missing some of configuration.

**Comment by Sean-Der** [comment] 2022-01-05 15:16
Hey @lamhai1401 

Sorry I didn't respond quick enough. Was this not a bug/what did you do to fix it?

thanks!

**Comment by lamhai1401** [comment] 2022-01-06 07:32
Not yet, my bad.  I have done more testing about this issue like the img above.
Following `data-channels-flow-control`, I have configured my `dc` config  after setting peer `connected`.

<img width="468" alt="Screen Shot 2022-01-06 at 14 07 57" src="https://user-images.githubusercontent.com/31619361/148343089-f28515fd-d214-4fd0-a30a-f78e19349000.png">

<img width="523" alt="Screen Shot 2022-01-06 at 14 31 02" src="https://user-images.githubusercontent.com/31619361/148345674-37f83975-bb43-441c-973b-9d7ba3b72c3f.png">

<img width="912" alt="Screen Shot 2022-01-06 at 14 09 31" src="https://user-images.githubusercontent.com/31619361/148343406-6e771457-648d-4f94-a20c-1fba13ee3662.png">

<img width="762" alt="Screen Shot 2022-01-06 at 14 08 27" src="https://user-images.githubusercontent.com/31619361/148343384-35098d70-83e0-42dc-a1b5-626fe2ff2fce.png">

When i checked log file, none of them was show. Therefore,  i think `data channel` buffer is ok but the message sent by `dc` was still lost randomly.

The following line appeared many times 

`mux ERROR: 2022/01/06 02:58:29 mux: ending readLoop dispatch error packetio.Buffer is full, discarding write`

Because i have 2 peers, one is `dc` and another is `media peer`, i'm not sure where it is.

Could you tell me some information about this issue for debugging.

Thank in advance!

**Comment by lamhai1401** [comment] 2022-01-07 12:18
@Sean-Der 
I found the root of this issue.

When we set  limit buffer amount and send too many data at same time, usually the buffer will stuck forever, i call `d.BufferedAmount()` and saw it's always increase

I remove all buffer configuration like  `data-channels-flow-control` example. It's work well.

**Comment by Sean-Der** [comment] 2022-04-18 20:22
Hey @lamhai1401 

Good news! This was fixed with 93b0f2a75eae5139362faf5346f0b6d53cfbf20d

Before if `pion/sctp` was overloaded we would interpret the error as fatal and shut down the packet processing in pion/webrc. Now we properly interpret it as a non-fatal error and continue.

**Closed by Sean-Der** 2022-04-18 20:22 UTC

**Comment by lamhai1401** [comment] 2022-04-19 04:39
> Hey @lamhai1401
> 
> Good news! This was fixed with [93b0f2a](https://github.com/pion/webrtc/commit/93b0f2a75eae5139362faf5346f0b6d53cfbf20d)
> 
> Before if `pion/sctp` was overloaded we would interpret the error as fatal and shut down the packet processing in pion/webrc. Now we properly interpret it as a non-fatal error and continue.


May i do this
```
ticker := time.NewTicker(20 * time.Millisecond)
for range ticker.C {
  _, err = endpoint.buffer.Write(buf)
  if !errors.Is(err, packetio.ErrFull) {
	  break
  }
}
```

Because i think `time.Sleep(20 * time.Millisecond)` have a latency.

**Comment by Sean-Der** [comment] 2022-04-19 18:58
@lamhai1401 I think we may remove the re-try entirely https://github.com/pion/webrtc/issues/2180 !

@iamcalledrob understood the issue/reproduced it so I am going to wait to make sure I don't break anything

**Comment by lamhai1401** [comment] 2022-04-20 04:05
@Sean-Der Here is my stdout after i added [93b0f2a](https://github.com/pion/webrtc/commit/93b0f2a75eae5139362faf5346f0b6d53cfbf20d)

New err was printed out `mux: ending readLoop dispatch error io: read/write on closed pipe`

<img width="949" alt="Screen Shot 2022-04-20 at 10 57 13" src="https://user-images.githubusercontent.com/31619361/164147758-8dedb2f2-4f9c-4e76-9979-76d18e81d70e.png">

**Comment by Sean-Der** [comment] 2022-04-20 04:37
@lamhai1401 that's interesting, that reads like `pion/sctp` (or another subsystem was closed)

Do you see anything happen before this? Are you able to reproduce this? Would you mind trying with 1368fe899e35805c648568fe30b71ae9231db9ad also, we dropped the retry logic and instead discard packets when we encounter back pressure.

**Comment by lamhai1401** [comment] 2022-04-20 05:14
> @lamhai1401 that's interesting, that reads like `pion/sctp` (or another subsystem was closed)
> 
> Do you see anything happen before this? Are you able to reproduce this? Would you mind trying with [1368fe8](https://github.com/pion/webrtc/commit/1368fe899e35805c648568fe30b71ae9231db9ad) also, we dropped the retry logic and instead discard packets when we encounter back pressure.

i will do a test today with [1368fe8](https://github.com/pion/webrtc/commit/1368fe899e35805c648568fe30b71ae9231db9ad)

>> Do you see anything happen before this?

i'm not sure where the cause is
Here is some issue i got

I' using `pion/turn` so i see lots of these line
```
turnc ERROR: 2022/04/19 06:18:57 fail to refresh permissions: all retransmissions failed for bh2ZsySX9fwZ3AzT
turnc ERROR: 2022/04/19 06:19:05 fail to refresh permissions: transaction closed
```

My webrtc peer connection got this line
```
Incoming unhandled RTP ssrc(321062147), OnTrack will not be fired. mid RTP Extensions required for Simulcast
```

And this is the most stranger thing
I'm peering from `pion` to `chrome` and `chrome` is offer.
After `connected`, `chrome` start to push VP9 and OPUS to `pion`. After a few min received that data, `chrome` still pushing data but `pion` randomly missing one of video/audio track data.
Try to re-handshake but its still, i must restart current `running process` by pm2.
Nothing to show on `pion` side,  but `chrome` export this error

![dtls](https://user-images.githubusercontent.com/31619361/164154462-75ec70d6-f499-464f-a22b-dcbac8724bd5.jpg)
